version: 2
meta:
  test_defaults: &test_defaults
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: run tests
          command: |
            ruby -v
            bundle exec rake
jobs:
  "ruby-2.5":
    <<: *test_defaults
    docker:
      - image: circleci/ruby:2.5
  "ruby-2.4":
    <<: *test_defaults
    docker:
      - image: circleci/ruby:2.4
  "ruby-2.3":
    <<: *test_defaults
    docker:
      - image: circleci/ruby:2.3
  publish:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Setup Rubygems
          command: .circleci/setup_rubygems.sh
      - run:
          name: Publish to Rubygems
          command: |
            set -u
            gem build circle_experiment.gemspec
            gem push "circle_experiment-${CIRCLE_TAG#v}.gem"

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.5":
          filters:
            tags:
              only: /v.*/
      - "ruby-2.4":
          filters:
            tags:
              only: /v.*/
      - "ruby-2.3":
          filters:
            tags:
              only: /v.*/
      - publish:
          requires:
            - "ruby-2.5"
            - "ruby-2.4"
            - "ruby-2.3"
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
